name: bg_flutter_job
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  loading_animation_widget: ^1.2.0+3

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
